### ISSUE TITLE
feat: exportar widget

### ISSUE THREAD

**Issue by msmosso** [fluiggers/fluig-vscode-extension#42]
**Descreva a melhoria**
Seria interessante adicionar a possibilidade de exportação de widget na extensão, é uma das funcionalidades restantes para que tenhamos o funcionamento completo.

**Ganhos**
Eliminar a necessidade do uso do Eclipse para exportar widgets

**Contexto adicional**
Ao exportar uma widget pela central de componentes do Fluig, é possível identificar que a url utilizada para envio é a https://endereco/portal/p/api/servlet/ApplicationUpload

O upload do arquivo é feito via formdata (enviando o arquivo .war)

![image](https://github.com/fluiggers/fluig-vscode-extension/assets/530015/5a60c3f5-d8b0-4167-b607-1e1b73af9744)

Enviei uma widget pela central e peguei o log da aba network: [fluig-dev.test.com.br.zip](https://github.com/fluiggers/fluig-vscode-extension/files/15155887/fluig-dev.test.com.br.zip)

**Comment by brunogasparetto** [comment]
Acho que a parte complicada é fazer o .war.

No Eclipse já tem o Java configurado junto com o Maven. Teria que confirmar como é feita essa compilação e colocando como dependência ter o Maven instalado de forma global né.

Mas concordo que é algo bem legal pra implementar.

**Comment by brunogasparetto** [comment]
Quando der faz um teste na branch que estou trabalhando.

https://github.com/brunogasparetto/fluig-vscode-extension/tree/widget

**Comment by msmosso** [comment]
Deu certo! Inicialmente tava retornando erro de fetch:

![image](https://github.com/fluiggers/fluig-vscode-extension/assets/530015/dbd51a88-4469-4d89-90bf-7823afca7179)

Resolvi alterar a configuração do servidor para que exigisse senha ao exportar. E deu certo!

![image](https://github.com/fluiggers/fluig-vscode-extension/assets/530015/42d91299-6fec-4a3e-b868-c9dd20b07fba)

Depois voltei a configuração do servidor para não mais exigir senha, e agora funciona de ambas as formas.

<img width="1074" alt="image" src="https://github.com/fluiggers/fluig-vscode-extension/assets/530015/f03f40e6-024b-4eaf-af7e-1960c9c137a0">


Muito bom! Parabéns!

**Comment by brunogasparetto** [comment]
A parte de revalidar a senha eu tinha colocado depois, talvez tenha dado algum problema. Aqui eu testo no Lab sem pedir confirmação e não tinha dado problema.

Mas ainda vou dar uma boa olhada em tudo antes de fazer a PR.

Pior de tudo é que entendi que o Eclipse não utiliza o Maven pra gerar o .war. Simplesmente cria um "zip" colocando os arquivos da widget nas pastas certas, salva como .war e envia pro Fluig.
